- hosts: all
  vars_files:
    - "vars/common/non-secrets.yml"
    - "vars/{{deploy_env}}/secrets.yml"
    - "vars/{{deploy_env}}/non-secrets.yml"

  tasks:
    - include: tasks/systemSetup.yml
    - include: tasks/installGo.yml
    - include: tasks/localDatabase.yml
    - include: tasks/API.yml

    # - include: tasks/serverStartup.yml

  handlers:
    - include: handlers/nginx.yml
