- hosts: all
  vars_files:
    - "vars/common/non-secrets.yml"
    - "vars/{{deploy_env}}/secrets.yml"
    - "vars/{{deploy_env}}/non-secrets.yml"

  tasks:
    - include: tasks/systemSetup.yml

    - include: tasks/installNode.yml
      when: app_language == "node"

    - include: tasks/installGo.yml
      when: app_language == "go"

    - include: tasks/localDatabase.yml
    - include: tasks/API.yml

  handlers:
    - include: handlers/nginx.yml
